version: "3.9"

services:
  pg:
    image: postgres:15.9-alpine3.20
    restart: always
    env_file:
      - .env
    ports:
      - 5555:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: redis:7.4.1-alpine3.20
    restart: always
    env_file: 
      - .env
    ports:
      - 7000:6379
    volumes:
      - redis:/data

volumes:
  postgres:
  redis:
