version: "3.9"

services:
  pg:
    image: postgres:15.9-alpine3.20
    ports:
      - 5557:5432
    restart: always
    env_file:
      - .env
    volumes:
      - "postgres:/var/lib/postgresql/data"

volumes:
  postgres:
