version: "3.9"

services:
  grafana:
    image: grafana/grafana-oss:11.4.0
    restart: always
    ports:
      - 3000:3000
    volumes: 
      - grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:v2.37.9
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

volumes:
  grafana_data:
  prometheus_data:
