global:
  scrape_interval:     5s #
  evaluation_interval: 5s # 

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['host.docker.internal:1337']

  - job_name: 'pet'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['host.docker.internal:2121']

  - job_name: 'auth'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['host.docker.internal:2122']

  - job_name: 'favorite'
    scrape_interval: 5s
    scrape_timeout: 5s

    static_configs:
      - targets: ['host.docker.internal:2123']
